import Link from "next/link";
import { Gift, Coins, Clock3 } from "lucide-react";
import { requireUser } from "@/lib/auth-server";
import { getRewards } from "@/lib/services/rewards";
import { getQuotaStatus } from "@/lib/quota";
import { RewardButton } from "@/components/rewards/reward-controls";
import { Card, CardContent } from "@/components/ui/card";
import { QuotaCard } from "@/components/quota-card";
import { formatDateTime } from "@/lib/utils";
export default async function RewardsPage() {
  const u = await requireUser(); const quota = await getQuotaStatus(u.id), d = await getRewards(u.id), r = d.rules;
  return <div className="space-y-6"><div><p className="eyebrow">LITTLE EFFORTS, EXTRA POSSIBILITIES</p><h1 className="page-title">我的积分</h1><p className="mt-2 text-sm text-muted">用每天的一点坚持，换更多开口的时间。</p></div>
    <div className="grid gap-4 md:grid-cols-[1.3fr_1fr]"><section className="hero-panel p-6 sm:p-8"><Coins className="text-brand-700" /><p className="mt-4 text-sm text-muted">可用积分</p><p className="mt-1 text-6xl font-semibold tracking-tighter" data-testid="points-balance">{d.points}</p><div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-sm">连续签到 <b>{d.streak}</b> 天 · 累计 <b>{d.totalDays}</b> 天</p><RewardButton action="checkin" disabled={d.checkedIn || !r.enabled}>{d.checkedIn ? "今日已签到" : `签到 +${r.checkin} 积分`}</RewardButton></div></section><QuotaCard quota={quota} /></div>
    <div className="grid gap-4 md:grid-cols-2"><Card><CardContent className="pt-6 sm:pt-6"><Gift className="text-brand-600" /><h2 className="mt-4 text-xl font-semibold">再练 {r.voucherMinutes} 分钟</h2><p className="mt-2 text-sm text-muted">兑换后 {r.voucherDays} 天有效。每日基础额度用完后自动使用，按到期先后扣减。</p><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><strong>{r.voucherCost} 积分 / 张</strong><RewardButton action="redeem" offer={{ cost: r.voucherCost, minutes: r.voucherMinutes, days: r.voucherDays }} disabled={d.points < r.voucherCost || !r.redemptionEnabled}>{r.redemptionEnabled ? "兑换分钟券" : "暂缓兑换"}</RewardButton></div><p className="mt-3 text-xs text-muted">每日最多兑换 {r.redemptionDailyLimit} 张；重复提交同一次兑换只扣一次。</p></CardContent></Card><Card><CardContent className="pt-6 sm:pt-6"><Clock3 className="text-muted" /><h2 className="mt-4 text-xl font-semibold">更多专题题库</h2><p className="mt-2 text-sm leading-7 text-muted">内容审核完成后再开放兑换。现有自由练习题库继续开放，不需要花积分解锁。</p><Link href="/practice" className="mt-5 inline-block text-sm text-brand-700 underline">先去现有题库练习 →</Link></CardContent></Card></div>
    <Card><CardContent className="pt-5"><h2 className="font-semibold">可用分钟券</h2>{d.credits.length ? <ul className="mt-3 divide-y divide-line">{d.credits.map(c => <li key={c.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>未预留余额 {(c.remainingSeconds / 60).toFixed(1)} / {c.totalSeconds / 60} 分钟</span><span className="text-xs text-muted">{formatDateTime(c.expiresAt)} 到期</span></li>)}</ul> : <p className="mt-3 text-sm text-muted">还没有有效分钟券，积分够了就能兑换。</p>}</CardContent></Card>
    <Card><CardContent className="pt-5"><h2 className="font-semibold">怎样获得积分</h2><p className="mt-3 text-sm leading-8 text-muted">签到 +{r.checkin}；完成有效录音练习 +{r.practice}（每天最多 {r.practiceLimit} 次）；在回答详情标记复盘并完成重练 +{r.review}（每天一次）。每日常规奖励最多 {r.dailyCap} 分，连续签到每满 7 天额外 +{r.milestone}。有效练习需完成会话，至少一段服务器解析录音满 5 秒、检测到的语音满 3 秒，不能用空录音领取。积分不自动过期，断签不扣积分；按 UTC+8 计算。</p></CardContent></Card>
    <Card><CardContent className="pt-5"><h2 className="font-semibold">积分明细 <span className="text-xs font-normal text-muted">最近 60 笔</span></h2>{d.ledger.length ? <ul className="mt-2 divide-y divide-line">{d.ledger.map(l => <li key={l.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm">{l.note}</p><p className="mt-1 text-xs text-muted">{formatDateTime(l.createdAt)}</p></div><span className={`shrink-0 font-semibold ${l.points > 0 ? "text-brand-700" : "text-muted"}`}>{l.points > 0 ? "+" : ""}{l.points}</span></li>)}</ul> : <p className="mt-4 text-sm text-muted">今天签到，留下第一笔积累。</p>}</CardContent></Card>
  </div>;
}
