"use client";
import { useActionState, useEffect, useState } from "react";
import { updateRewardsAction, adjustPointsAction, extendCreditAction } from "@/app/actions/rewards";
import type { AppSettings } from "@/lib/settings";
import { Button } from "@/components/ui/button";
const names = { checkin: "每日签到积分", practice: "有效练习积分", review: "复盘重练积分", milestone: "连续 7 天奖励", dailyCap: "每日常规积分上限", practiceLimit: "每日练习奖励次数", voucherCost: "每张分钟券积分价格", voucherMinutes: "每张分钟券分钟数", voucherDays: "分钟券有效天数", redemptionDailyLimit: "每日兑换次数上限" };
const inputClass = "min-h-11 w-full rounded-xl border border-line bg-surface px-3 text-sm";
function Message({ state }: { state: { error?: string; ok?: string } | null }) { return state && <p role="status" className={`text-sm ${state.error ? "text-red-700" : "text-brand-700"}`}>{state.error ?? state.ok}</p>; }
export function RewardsAdminForms({ settings, users }: { settings: AppSettings["rewards"]; users: { id: string; name: string; email: string }[] }) {
  const [state, save, saving] = useActionState(updateRewardsAction, null);
  const [adjust, submit, adjusting] = useActionState(adjustPointsAction, null);
  const [extend, extension, extending] = useActionState(extendCreditAction, null);
  const [key, setKey] = useState(""), [extensionKey, setExtensionKey] = useState("");
  useEffect(() => { setKey(crypto.randomUUID()); setExtensionKey(crypto.randomUUID()); }, []);
  return <div className="space-y-5"><form action={save} className="surface-card space-y-5 rounded-3xl border border-line bg-surface p-5"><h2 className="font-semibold">奖励与兑换规则</h2><div className="flex flex-wrap gap-5 text-sm"><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="enabled" defaultChecked={settings.enabled} />启用签到与练习奖励</label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" name="redemptionEnabled" defaultChecked={settings.redemptionEnabled} />开放分钟券兑换</label></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(names).map(([key, label]) => <label key={key} className="space-y-2 text-sm"><span>{label}</span><input className={inputClass} type="number" step="1" min={key.startsWith("voucher") || key === "redemptionDailyLimit" ? 1 : 0} name={key} defaultValue={settings[key as keyof typeof names]} required /></label>)}</div><Message state={state} /><Button type="submit" disabled={saving}>{saving ? "保存中…" : "保存奖励规则"}</Button><p className="text-xs text-muted">全站暂停或月度预算耗尽时自动阻止新兑换。暂停奖励不会删除已获得积分。</p></form>
    <form action={submit} className="surface-card space-y-4 rounded-3xl border border-line bg-surface p-5"><h2 className="font-semibold">积分补发 / 扣回</h2><input type="hidden" name="requestId" value={key} /><label className="block space-y-2 text-sm"><span>用户</span><select aria-label="用户" className={inputClass} name="userId" required>{users.map(u => <option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label><label className="block space-y-2 text-sm"><span>调整积分（负数表示扣回）</span><input className={inputClass} type="number" name="points" min="-10000" max="10000" required /></label><label className="block space-y-2 text-sm"><span>调整原因</span><input className={inputClass} name="note" minLength={3} maxLength={200} required /></label><Message state={adjust} /><Button type="submit" disabled={adjusting || !!adjust?.ok}>{adjusting ? "处理中…" : "提交积分调整"}</Button><p className="text-xs text-muted">每次提交均留有记录。提交成功后刷新页面可进行下一笔调整。</p></form>
    <form action={extension} className="surface-card space-y-4 rounded-3xl border border-line bg-surface p-5"><h2 className="font-semibold">服务中断补偿：分钟券延期</h2><input type="hidden" name="requestId" value={extensionKey} /><label className="block space-y-2 text-sm"><span>分钟券编号</span><input className={inputClass} name="creditId" required /></label><label className="block space-y-2 text-sm"><span>延期天数</span><input className={inputClass} type="number" min="1" max="90" name="days" defaultValue={7} required /></label><label className="block space-y-2 text-sm"><span>延期原因</span><input className={inputClass} name="note" minLength={3} maxLength={200} required /></label><Message state={extend} /><Button type="submit" disabled={extending || !!extend?.ok}>确认延期</Button></form>
  </div>;
}
